name: Bug Report
description: Report a bug or unexpected behavior in Raptor Static
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible.

  - type: dropdown
    id: runtime
    attributes:
      label: Runtime Environment
      description: Which JavaScript runtime are you using?
      options:
        - Deno
        - Node.js
        - Bun
        - Multiple runtimes
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Static Version
      description: Which version of Raptor Static are you using?
      placeholder: "e.g., 0.14.0"
    validations:
      required: true

  - type: input
    id: framework-version
    attributes:
      label: Framework Version
      description: Which version of Raptor Framework are you using?
      placeholder: "e.g., 0.14.0"
    validations:
      required: true

  - type: input
    id: runtime-version
    attributes:
      label: Runtime Version
      description: Which version of your runtime are you using?
      placeholder: "e.g., Deno 2.1.0, Node.js 20.10.0, Bun 1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Minimal Reproduction
      description: Provide the smallest amount of code that reproduces the issue
      placeholder: |
        import { Kernel } from "@raptor/kernel";
        import { ErrorHandler } from "@raptor/error";

        const app = new Kernel();

        const errorHandler = new ErrorHandler();

        // Your reproduction code here
      render: typescript
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens? Include error messages if applicable.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information that might help
